# Generated by Django 3.2.5 on 2021-07-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='coments',
            new_name='comments',
        ),
    ]
